### ISSUE TITLE
Add subpack objects

### ISSUE THREAD

**Issue by axxroytovu** [axxroytovu/magic-search-engine#1]
Plan to add nonstandard "pack" and "deck" objects to facilitate https://github.com/axxroytovu/MTG-Median-Analysis. These include:

- Prerelease pack promo cards
- The variable rare in set jumpstart packs
- The "collector sample packs" from commander precons
- Theme boosters
- Box topper packs
- Bundle promo packs

@taw I assume not, but do you want me to pull these back up into the main repo?

**Comment by taw** [comment]
For 19+random Jumpstarts, [I'm currently using human-readable annotations like this](https://mtg.wtf/deck/dmu/arcane-mischief).

Technically this could be modelled as `dmu-jumpstart.yaml` with 20 variants, each with 19 unique sheets, but I don't know if this is a good way to present this data.

For other booster types, could you remind me what they are?

**Comment by axxroytovu** [comment]
The way I was going to handle jumpstart boosters was to have a separate (as an example) "Arcane Mystic Sealed Booster" object, which contains the `dmu/Arcane Myschief.txt` deck and a `dmu-blue-rare-mythic.yaml` "pack", since both decks and boosters are stored in the same format for my uses.

- Prerelease pack promo cards: a "pack" that just contains the one stamped card that comes in a prerelease pack.
- The "collector sample packs" from commander precons: https://www.youtube.com/watch?v=EPU8vqUQE6I&ab_channel=LRRMTG
- Theme boosters: explained lower down here: https://magic.wizards.com/en/news/feature/zendikar-rising-product-overview-2020-09-02
- Box topper packs: Like the Zendikar Expedition box toppers
- Bundle promo packs: The promo card and lands that come in fat packs or gift bundles.

**Comment by taw** [comment]
I don't think I'd want "boosters" of 1-2 cards right now. 

Are theme boosters randomized or preconstructed? Either way, they should be OK?

For other randomized products, if we have reliable information about them, and they fit the current system, I guess they could be represented. I know there were some nonstandard faction boosters for prereleases and other weird things as well. For a while most prereleases did this.

By the way I could imagine some future system where there's "product" object which contains a bunch of preconstructed and randomized subproducts, and it would make sense to have those micro-boosters there, but right now I think we should pass on that. ([by the way there's this](https://mtg.wtf/product) from mtgjson, but I never really integrated it with anything)

We could do something like this:

```yaml
name: "Streets of New Capenna Commander Deck Obscura Operation"
contents:
- precon:
  - set: ncc
  - name: "Obscura Operation"
- boosters:
  - code: "ncc-collector-sampler"
  - count: 1
```

```yaml
name: "March of the Machine Draft Booster Box"
contents:
- boosters:
  - code:  mom
  - count: 36
# buyabox promo
- card:
  - set: mom
  - number: 387
  - foil: true
```

```yaml
name: "Return to Ravnica Prerelease Pack Azorius"
contents:
- boosters
  - code: rtr
  - count: 5
- boosters:
  - code: rtr-prerelease-azorius
  - count: 1
- card:
   # Archon of the Triumvirate
  - set: prtr
  - number: "142★"
```

etc.

I don't think I'd have time for this right now, but I think the concept could work.
